# Generated by Django 2.2.12 on 2021-03-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=1000)),
            ],
        ),
    ]
